---
- name: gather facts
  hosts: jumpbox
  roles:
    - role: facts
- name: setup
  hosts: all
  become: yes
  roles:
    - role: basic-setup
- name: install haproxy
  hosts: frontends
  become: yes
  roles:
    - role: haproxy
- name: install & configure tomcat
  hosts: apps
  become: yes
  roles:
    - role: tomcat
- name: install & configure postgres
  hosts: appdbs
  become: yes
  roles:
    - role: geerlingguy.postgresql
