- hosts: jumpbox
#  become: yes
  roles:
     - network
     - keypair
     - securitygroups
  tasks:
##Create Fronend Instance
  - name: Create frontend instance
    include_role:
       name: pro_instances
       vars_from: frontend.yml
###Create App1 server
  - name: Create app1 instance
    include_role:
       name: pro_instances
       vars_from: app1.yml
##Create App2 server
  - name: Create app2 instance
    include_role:
       name: pro_instances
       vars_from: app2.yml
##Create DB server
  - name: Create db instance
    include_role:
       name: pro_instances
       vars_from: db.yml
  - name: Gather facts
    include_role: 
       name: facts
    tags:
     - test_inventory
