---
# Variable configuration.
- include_tasks: variables.yml
  static: no

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  static: no

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  static: no

- include_tasks: initialize.yml
- include: configure.yml

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: started
    enabled: yes

# Configure PostgreSQL.
- include_tasks: databases.yml
- include_tasks: users.yml
